default: &default
  adapter: oracle_enhanced
  username: system
  password: 122
  host: localhost
  port: 1521
  database: FREE

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
